### PR TITLE
Forward consumed message to dead letters on an exception.

### LINKED ISSUE #37: deadLetterQueue
Currently when an unknown Exception is encountered the error message is logged to console and the message is deleted. https://github.com/DoSomething/mbc-transactional-email/blob/master/src/MBC_TransactionalEmail_Consumer.php#L110-L115

Add support for sending Exception cases to `deadLetterQueue` to retain the original message and trigger alerts.

- Test Case: Invalid Mandrill Key
produces:
```
Error sending transactional email to: testrecipient+1470322320760@dosomething.org. Error: Invalid API key
```

### PR DESCRIPTION
**Pull request by sergii-tkachenko**
Fixes an issue when messages consumed which encountered unknown exception are deleted rather then forwarded to the Dead Letters queue.
Closes #37.

### CODE REVIEW

File: src/MBC_TransactionalEmail_Consumer.php [hunk 1]
```diff
@@ -105,14 +105,14 @@ public function consumeTransactionalQueue($payload) {
...
         echo '**ALERT: ' . $e->getMessage(), PHP_EOL;
-        parent::deadLetter($this->message, 'MBC_TransactionalEmail_Consumer->consumeTransactionalQueue() Error', $e->getMessage());
         $this->messageBroker->sendAck($this->message['payload']);
       }
       else {
         echo 'Error sending transactional email to: ' . $this->message['email'] . '. Error: ' . $e->getMessage() . PHP_EOL;
         $errorDetails = $e->getMessage();
         $this->messageBroker->sendAck($this->message['payload']);
       }
+      parent::deadLetter($this->message, 'MBC_TransactionalEmail_Consumer->consumeTransactionalQueue() Error', $e->getMessage());
```
Comment (DeeZone) [inline src/MBC_TransactionalEmail_Consumer.php]: I guess you could do this for all Exceptions:
```
echo '**ALERT: ' . $e->getMessage(), PHP_EOL;
$this->messageBroker->sendAck($this->message['payload']);
parent::deadLetter($this->message, 'MBC_TransactionalEmail_Consumer->consumeTransactionalQueue() Error', $e->getMessage());
```

Comment (sergii-tkachenko) [inline src/MBC_TransactionalEmail_Consumer.php]: So should I just remove `if`s and keep lines you posted?

Comment (DeeZone) [inline src/MBC_TransactionalEmail_Consumer.php]: 👍

**Comment by sergii-tkachenko** [comment]
```
PHPUnit 4.0.20 by Sebastian Bergmann.

.

Time: 48 ms, Memory: 6.00MB

OK (1 test, 1 assertion)
```

**Comment by DeeZone** [comment]
👍
